import React from "react";
import type {Metadata} from "next"
import "./globals.css";
import localFont from 'next/font/local'
import ReduxProvider from "@/redux/provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const myFont = localFont({
    src: '../../public/fonts/YekanBakhFaNum-Regular.woff2',
})

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="fa" dir="rtl">
        <body className={myFont.className}>
        <ReduxProvider>
            {children}
        </ReduxProvider>
        </body>
        </html>
    );
}
